//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteoCrawler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MutuelleBDEntities : DbContext
    {
        public MutuelleBDEntities()
            : base("name=MutuelleBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Meteo> Meteo { get; set; }
        public virtual DbSet<Station2> Station2 { get; set; }
        public virtual DbSet<MeteoWithDep> MeteoWithDep { get; set; }
    }
}
