//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteoCrawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station2
    {
        public int idStation { get; set; }
        public string departement { get; set; }
        public string nom { get; set; }
        public string code { get; set; }
    }
}
